// TypeScript declarations required for some reserved words...
// TODO - declaring global vars here throws typescript errors...
// - just defining them in index.ts for now
// declare var process: any;
